config/routes.rb
Litmus::Application.routes.draw do
  get "home/index"

  resources :test_cases

  resources :test_suites do
    resources :test_cases
  end

  resources :projects do
    resources :test_suites
  end

  match 'search' => 'search#index'
  match 'test_suites/:id/test_runs/new' => 'test_runs#new'
  match 'test_suites/:id/test_runs/create' => 'test_runs#create'
  match 'test_runs' => 'test_runs#index'

  match 'results/add' => 'results#create'

  root :to => 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :test_suites

  define_index do
    indexes title
    indexes description
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    # Create Test Cases array.
    @test_cases = []
    for test_suite in @project.test_suites.each
      for test_case in test_suite.test_cases.each
        @test_cases.append test_case
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_area :description, :size => "5x5"%><br />
    <%= f.submit "update", :class => 'btn btn-success' %>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>
    Editing
    <%= @project.title %>
  </h1>
</div>

<%= render 'form' %>

<%= link_to 'Cancel', @project %>

app/views/projects/index.html.erb
<div class="page-header">
  <h1>Projects</h1>
</div>

<% if @projects.empty? == false %>
<table class="table table-bordered table-striped" >
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.title, project %></td>
        <td><%= link_to raw('<i class="icon-trash"></i>trash'), project, method: :delete, :class => 'btn btn-small' %></td>
      </tr>
    <% end %>
</tbody>
</table>
<% else %>
  <div class="alert alert-info">
    <p>
      You are not managing any projects.
      <%= link_to 'Create one!', new_project_path %>
    </p>
  </div>
<% end %>

<%= link_to raw('<i class="icon-plus icon-white"></i>&nbsp;Project'), new_project_path, :class => 'btn btn-success'%> 

app/views/projects/new.html.erb
<div class="page-header">
  <h1>New Project</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="page-header">
  <h1>
    <%= @project.title %>
    <small>
      <%= link_to 'edit', edit_project_path(@project) %>
    </small>
  </h1>
</div>

<%= render :partial => 'shared/notice_display', :notice => notice %>

<dl>
  <dt>Description:</dt>
  <dd><%= simple_format(@project.description) %></dd>
</dl>

<% if @project.test_suites.empty? == false %>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>
  
  <tbody>
    <% @project.test_suites.each do |test_suite| %>
      <tr>
        <td><%= link_to test_suite.title, test_suite %></td>
        <td><%= link_to raw('<i class="icon-trash"></i>trash'), test_suite, method: :delete, :class => 'btn btn-small' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="alert alert-info">
    <p>
    <%= @project.title %> has no test suites.
    <%= link_to 'Create one!', new_project_test_suite_path(@project) %>
    </p>
  </div>
<% end %>
<%= link_to raw('<i class="icon-plus icon-white"></i>&nbsp;Test Suite'), new_project_test_suite_path(@project), :class => 'btn btn-success'%> 

</div>