config/routes.rb
Litmus::Application.routes.draw do
  get "home/index"

  resources :test_cases

  resources :test_suites do
    resources :test_cases
  end

  resources :projects do
    resources :test_suites
  end

  match 'search' => 'search#index'
  match 'test_suites/:id/test_runs/new' => 'test_runs#new'
  match 'test_suites/:id/test_runs/create' => 'test_runs#create'
  match 'test_runs' => 'test_runs#index'

  match 'results/add' => 'results#create'

  root :to => 'home#index'

end

app/models/test_run.rb
class TestRun < ActiveRecord::Base
  belongs_to :test_case
  has_many :results
end

app/controllers/test_runs_controller.rb
class TestRunsController < ApplicationController

  def index
    @test_runs = TestRun.all
  end

  # GET /test_suites/1/test_runs/new
  def new
    @test_suite = TestSuite.find(params[:id])
  end

  # POST /test_suites/1/test_runs/create
  def create
    runs = []
    params.each do |k, v|
      runs << {:test_case_id => k.match('\d+')[0]} if k.include?('test_case_')
    end

    if TestRun.create runs
      redirect_to '/test_runs/', notice: "Test Run was successfully created." 
    else
      render action: "new"
    end
  end

end

app/helpers/test_runs_helper.rb
module TestRunsHelper
end

app/views/test_runs/index.html.erb
<div class="page-header">
  <h1>Test Runs</h1>
</div>

<%= render :partial => 'shared/notice_display', :notice => notice %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Suite</th>
      <th>Case</th>
      <th>Result</th>
    </tr>
  </thead>

  <tbody>
<% @test_runs.each do |test_run| %>
  <tr>
    <td><%= link_to test_run.test_case.test_suite.title, test_suite_path(test_run.test_case.test_suite) %></td>
    <td><%= link_to test_run.test_case.title,  test_case_path(test_run.test_case) %></td>
    <td><%= select_tag 'test_run_' + test_run.id.to_s, options_for_select(Result::STATUSES, test_run.results.last_updated)  %></td>
  </tr>
<% end %>
</table>

app/views/test_runs/new.html.erb
<div class="page-header">
  <h1>
    <%= @test_suite.title %>
    <small>
      <%= link_to 'edit', edit_project_test_suite_path(@test_suite) %>
    </small>
  </h1>
</div>

<%= render :partial => 'shared/notice_display', :notice => notice %>

<dl>
  <dt>Project:</dt>
  <dd><%= link_to @test_suite.project.title, @test_suite.project %></dd>
  <dt>Description:</dt>
  <dd><%= simple_format(@test_suite.description) %></dd>
</dl>

<h2>Test Cases</h2>

<% if @test_suite.test_cases.empty? == false %>
  <p>
    <span>select: </span>
    <%= link_to 'all' %> |
    <%= link_to 'none' %>
    </p>

  <%= form_tag './create', :method => "post" %>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Add</th>
        <th>Title</th>
      </tr>
    </thead>
    <tbody>
      <% @test_suite.test_cases.each do |test_case| %>
          <tr>
            <td style="width: 25px">
              <%= check_box_tag 'test_case_'+test_case.id.to_s %>
            </td>
            <td><%= link_to test_case.title, test_case %></td>
            <td><%= link_to raw('<i class="icon-trash"></i>trash'), test_case, method: :delete, :class => 'btn btn-small' %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
  <%= submit_tag "Add Test Runs", :class => 'btn btn-success' %>
<% else %>
  <div class="alert alert-info">
    <p>
    <%= @test_suite.title %> has no test cases.
    <%= link_to 'Create one!', new_test_suite_test_case_path(@test_suite) %>
    </p>
  </div>
<% end %>