config/routes.rb
Litmus::Application.routes.draw do
  get "home/index"

  resources :test_cases

  resources :test_suites do
    resources :test_cases
  end

  resources :projects do
    resources :test_suites
  end

  match 'search' => 'search#index'
  match 'test_suites/:id/test_runs/new' => 'test_runs#new'
  match 'test_suites/:id/test_runs/create' => 'test_runs#create'
  match 'test_runs' => 'test_runs#index'

  match 'results/add' => 'results#create'

  root :to => 'home#index'

end

app/models/test_suite.rb
class TestSuite < ActiveRecord::Base
  belongs_to :project
  has_many :test_cases

  define_index do
    indexes title
    indexes description
  end
end

app/controllers/test_suites_controller.rb
class TestSuitesController < ApplicationController
  # GET /test_suites
  # GET /test_suites.json
  def index
    @test_suites = TestSuite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @test_suites }
    end
  end

  # GET /test_suites/1
  # GET /test_suites/1.json
  def show
    @test_suite = TestSuite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test_suite }
    end
  end

  # GET /test_suites/new
  # GET /test_suites/new.json
  def new
    @test_suite = TestSuite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_suite }
    end
  end

  # GET /test_suites/1/edit
  def edit
    @test_suite = TestSuite.find(params[:id])
  end

  # POST /test_suites
  # POST /test_suites.json
  def create
    @test_suite = TestSuite.new(params[:test_suite])

    respond_to do |format|
      if @test_suite.save
        format.html { redirect_to @test_suite, notice: 'Test suite was successfully created.' }
        format.json { render json: @test_suite, status: :created, location: @test_suite }
      else
        format.html { render action: "new" }
        format.json { render json: @test_suite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /test_suites/1
  # PUT /test_suites/1.json
  def update
    @test_suite = TestSuite.find(params[:id])

    respond_to do |format|
      if @test_suite.update_attributes(params[:test_suite])
        format.html { redirect_to @test_suite, notice: 'Test suite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test_suite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_suites/1
  # DELETE /test_suites/1.json
  def destroy
    @test_suite = TestSuite.find(params[:id])
    @test_suite.destroy

    respond_to do |format|
      format.html { redirect_to test_suites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/test_suites_helper.rb
module TestSuitesHelper
end

app/views/test_suites/_form.html.erb
<%= form_for(@test_suite) do |f| %>
  <% if @test_suite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_suite.errors.count, "error") %> prohibited this test_suite from being saved:</h2>

      <ul>
      <% @test_suite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_area :description, :size => '5x5' %>
    <%= f.hidden_field :project_id, :value => (params[:project_id] or @test_suite.project_id) %></br>
    <%= f.submit "update", :class => 'btn btn-success' %>
<% end %>

app/views/test_suites/edit.html.erb
<div class="page-header">
  <h1>
    Editing
    <%= @test_suite.title %>
  </h1>
</div>

<%= render 'form' %>

<%= link_to 'Cancel', @test_suite %>

app/views/test_suites/index.html.erb
<div class="page-header">
  <h1>Test Suites</h1>
</div>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @test_suites.each do |test_suite| %>
  <tr>
    <td><%= test_suite.title %></td>
    <td><%= link_to 'Show', test_suite %></td>
    <td><%= link_to 'Edit', edit_test_suite_path(test_suite) %></td>
    <td><%= link_to 'Destroy', test_suite, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Test suite', new_test_suite_path %>

app/views/test_suites/new.html.erb
<div class="page-header">
  <h1>New Test Suite</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', project_path(params[:project_id]) %>

app/views/test_suites/show.html.erb
<div class="page-header">
  <h1>
    <%= @test_suite.title %>
    <small>
      <%= link_to 'edit', edit_project_test_suite_path(@test_suite) %>
    </small>
  </h1>
</div>

<%= render :partial => 'shared/notice_display', :notice => notice %>

<dl>
  <dt>Project:</dt>
  <dd><%= link_to @test_suite.project.title, @test_suite.project %></dd>
  <dt>Description:</dt>
  <dd><%= simple_format(@test_suite.description) %></dd>
</dl>

<h2>Test Cases</h2>

<% if @test_suite.test_cases.empty? == false %>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @test_suite.test_cases.each do |test_case| %>
      <tr>
        <td><%= link_to test_case.title, test_case %></td>
        <td><%= link_to raw('<i class="icon-trash"></i>trash'), test_case, method: :delete, :class => 'btn btn-small' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="alert alert-info">
    <p>
    <%= @test_suite.title %> has no test cases.
    <%= link_to 'Create one!', new_test_suite_test_case_path(@test_suite) %>
    </p>
  </div>
<% end %>

<p><%= link_to raw('<i class="icon-plus icon-white"></i>&nbsp;Test Case'), new_test_suite_test_case_path(@test_suite), :class => 'btn btn-success'%></p>